@startuml

title __APP's Class Diagram__\n

  namespace  {
    namespace om.example.wemeet {
      class com.example.wemeet.AddBugActivity {
      }
    }
  }
  

  namespace  {
    namespace om.example.wemeet {
      class com.example.wemeet.BuildConfig {
      }
    }
  }
  

  namespace  {
    namespace om.example.wemeet {
      class com.example.wemeet.ChangeLevelActivity {
      }
    }
  }
  

  namespace  {
    namespace om.example.wemeet {
      class com.example.wemeet.InitActivity {
      }
    }
  }
  

  namespace  {
    namespace om.example.wemeet {
      class com.example.wemeet.LoginActivity {
      }
    }
  }
  

  namespace  {
    namespace om.example.wemeet {
      class com.example.wemeet.MainActivity {
      }
    }
  }
  

  namespace  {
    namespace om.example.wemeet {
      class com.example.wemeet.ShowQuestionActivity {
      }
    }
  }
  

  namespace  {
    namespace om.example.wemeet {
      class com.example.wemeet.ShowVirusActivity {
      }
    }
  }
  

  namespace  {
    namespace om.example.wemeet {
      class com.example.wemeet.UserCenterActivity {
      }
    }
  }
  

  namespace  {
    namespace om.example.wemeet {
      namespace pojo {
        class com.example.wemeet.pojo.Bug {
        }
      }
    }
  }
  

  namespace  {
    namespace om.example.wemeet {
      namespace pojo {
        class com.example.wemeet.pojo.BugContent {
        }
      }
    }
  }
  

  namespace  {
    namespace om.example.wemeet {
      namespace pojo {
        interface com.example.wemeet.pojo.BugInterface {
        }
      }
    }
  }
  

  namespace  {
    namespace om.example.wemeet {
      namespace pojo {
        class com.example.wemeet.pojo.BugProperty {
        }
      }
    }
  }
  

  namespace  {
    namespace om.example.wemeet {
      namespace pojo {
        class com.example.wemeet.pojo.CatcherBugKey {
        }
      }
    }
  }
  

  namespace  {
    namespace om.example.wemeet {
      namespace pojo {
        class com.example.wemeet.pojo.CatcherBugRecord {
        }
      }
    }
  }
  

  namespace  {
    namespace om.example.wemeet {
      namespace pojo {
        class com.example.wemeet.pojo.ChoiceQuestion {
        }
      }
    }
  }
  

  namespace  {
    namespace om.example.wemeet {
      namespace pojo {
        class com.example.wemeet.pojo.ContentDesc {
        }
      }
    }
  }
  

  namespace  {
    namespace om.example.wemeet {
      namespace pojo {
        class com.example.wemeet.pojo.Message {
        }
      }
    }
  }
  

  namespace  {
    namespace om.example.wemeet {
      namespace pojo {
        class com.example.wemeet.pojo.Moment {
        }
      }
    }
  }
  

  namespace  {
    namespace om.example.wemeet {
      namespace pojo {
        class com.example.wemeet.pojo.NarrativeQuestion {
        }
      }
    }
  }
  

  namespace  {
    namespace om.example.wemeet {
      namespace pojo {
        class com.example.wemeet.pojo.VirusPoint {
        }
      }
    }
  }
  

  namespace  {
    namespace om.example.wemeet {
      namespace pojo {
        namespace user {
          class com.example.wemeet.pojo.user.User {
          }
        }
      }
    }
  }
  

  namespace  {
    namespace om.example.wemeet {
      namespace pojo {
        namespace user {
          interface com.example.wemeet.pojo.user.UserInterface {
          }
        }
      }
    }
  }
  

  namespace  {
    namespace om.example.wemeet {
      namespace util {
        class com.example.wemeet.util.MarkerInfo {
        }
      }
    }
  }
  

  namespace  {
    namespace om.example.wemeet {
      namespace util {
        class com.example.wemeet.util.MathUtil {
        }
      }
    }
  }
  

  namespace  {
    namespace om.example.wemeet {
      namespace util {
        class com.example.wemeet.util.NetworkUtil {
        }
      }
    }
  }
  

  namespace  {
    namespace om.example.wemeet {
      namespace util {
        class com.example.wemeet.util.ReturnVO {
        }
      }
    }
  }
  

  com.example.wemeet.AddBugActivity -up-|> androidx.appcompat.app.AppCompatActivity
  com.example.wemeet.ChangeLevelActivity -up-|> androidx.fragment.app.DialogFragment
  com.example.wemeet.InitActivity -up-|> androidx.appcompat.app.AppCompatActivity
  com.example.wemeet.LoginActivity -up-|> androidx.appcompat.app.AppCompatActivity
  com.example.wemeet.MainActivity -up-|> androidx.appcompat.app.AppCompatActivity
  com.example.wemeet.ShowQuestionActivity -up-|> androidx.fragment.app.DialogFragment
  com.example.wemeet.ShowVirusActivity -up-|> androidx.fragment.app.DialogFragment
  com.example.wemeet.UserCenterActivity -up-|> androidx.appcompat.app.AppCompatActivity
  com.example.wemeet.pojo.Bug .up.|> java.io.Serializable
  com.example.wemeet.pojo.Bug o-- com.example.wemeet.pojo.BugProperty : bugProperty
  com.example.wemeet.pojo.Bug o-- com.example.wemeet.pojo.ChoiceQuestion : choiceQuestion
  com.example.wemeet.pojo.Bug o-- com.example.wemeet.pojo.Moment : moment
  com.example.wemeet.pojo.Bug o-- com.example.wemeet.pojo.NarrativeQuestion : narrativeQuestion
  com.example.wemeet.pojo.Bug o-- com.example.wemeet.pojo.user.User : planter
  com.example.wemeet.pojo.Bug o-- com.example.wemeet.pojo.VirusPoint : virusPoint
  com.example.wemeet.pojo.BugContent .up.|> java.io.Serializable
  com.example.wemeet.pojo.BugProperty .up.|> java.io.Serializable
  com.example.wemeet.pojo.BugProperty o-- com.example.wemeet.pojo.BugContent : bugContent
  com.example.wemeet.pojo.BugProperty o-- com.example.wemeet.pojo.Message : message
  com.example.wemeet.pojo.BugProperty o-- com.example.wemeet.pojo.user.User : planter
  com.example.wemeet.pojo.CatcherBugKey .up.|> java.io.Serializable
  com.example.wemeet.pojo.CatcherBugRecord .up.|> java.io.Serializable
  com.example.wemeet.pojo.CatcherBugRecord o-- com.example.wemeet.pojo.user.User : catcher
  com.example.wemeet.pojo.CatcherBugRecord o-- com.example.wemeet.pojo.BugProperty : caughtBug
  com.example.wemeet.pojo.CatcherBugRecord o-- com.example.wemeet.pojo.CatcherBugKey : id
  com.example.wemeet.pojo.ChoiceQuestion .up.|> java.io.Serializable
  com.example.wemeet.pojo.ChoiceQuestion -up-|> com.example.wemeet.pojo.BugContent
  com.example.wemeet.pojo.ChoiceQuestion o-- com.example.wemeet.pojo.ContentDesc : question
  com.example.wemeet.pojo.ContentDesc .up.|> java.io.Serializable
  com.example.wemeet.pojo.Message .up.|> java.io.Serializable
  com.example.wemeet.pojo.Message o-- com.example.wemeet.pojo.ContentDesc : contentDesc
  com.example.wemeet.pojo.Message o-- com.example.wemeet.pojo.user.User : user
  com.example.wemeet.pojo.Moment .up.|> java.io.Serializable
  com.example.wemeet.pojo.Moment -up-|> com.example.wemeet.pojo.BugContent
  com.example.wemeet.pojo.Moment o-- com.example.wemeet.pojo.ContentDesc : contentDesc
  com.example.wemeet.pojo.NarrativeQuestion .up.|> java.io.Serializable
  com.example.wemeet.pojo.NarrativeQuestion -up-|> com.example.wemeet.pojo.BugContent
  com.example.wemeet.pojo.NarrativeQuestion o-- com.example.wemeet.pojo.ContentDesc : question
  com.example.wemeet.pojo.VirusPoint .up.|> java.io.Serializable
  com.example.wemeet.pojo.VirusPoint -up-|> com.example.wemeet.pojo.BugContent
  com.example.wemeet.pojo.user.User .up.|> java.io.Serializable
  com.example.wemeet.util.MarkerInfo o-- com.example.wemeet.pojo.Bug : bug


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
