@startuml

title __USER's Class Diagram__\n

  namespace  {
    namespace om.example.wemeet {
      namespace pojo {
        namespace user {
          class com.example.wemeet.pojo.user.User {
              - catchRecords : Set<CatcherBugRecord>
              - email : String
              - grade : Integer
              - id : Long
              - name : String
              - password : String
              - phoneNumber : String
              - plantBugs : List<BugProperty>
              - role : int
              - score : Double
              + User()
              + equals()
              + getCatchRecords()
              + getEmail()
              + getGrade()
              + getId()
              + getName()
              + getPassword()
              + getPhoneNumber()
              + getPlantBugs()
              + getRole()
              + getScore()
              + hashCode()
              + setCatchRecords()
              + setEmail()
              + setGrade()
              + setId()
              + setName()
              + setPassword()
              + setPhoneNumber()
              + setPlantBugs()
              + setRole()
              + setScore()
              + toString()
          }
        }
      }
    }
  }
  

  namespace  {
    namespace om.example.wemeet {
      namespace pojo {
        namespace user {
          interface com.example.wemeet.pojo.user.UserInterface {
              {abstract} + changeScoreOfUser()
              {abstract} + getPlantBugsByUserEmail()
              {abstract} + getUserByEmail()
              {abstract} + login()
              {abstract} + updateUser()
          }
        }
      }
    }
  }
  

  com.example.wemeet.pojo.user.User .up.|> java.io.Serializable


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
