@startuml

title __UTIL's Class Diagram__\n

  namespace  {
    namespace om.example.wemeet {
      namespace util {
        class com.example.wemeet.util.MarkerInfo {
            - caught : boolean
            - userAnswer : String
            + MarkerInfo()
            + equals()
            + getBug()
            + getUserAnswer()
            + hashCode()
            + isCaught()
            + setBug()
            + setCaught()
            + setUserAnswer()
            + toString()
            # canEqual()
        }
      }
    }
  }
  

  namespace  {
    namespace om.example.wemeet {
      namespace util {
        class com.example.wemeet.util.MathUtil {
            {static} - EARTH_RADIUS : double
            {static} + getDistance()
            {static} - rad()
        }
      }
    }
  }
  

  namespace  {
    namespace om.example.wemeet {
      namespace util {
        class com.example.wemeet.util.NetworkUtil {
            {static} - retrofit : Retrofit
            {static} + getRetrofit()
        }
      }
    }
  }
  

  namespace  {
    namespace om.example.wemeet {
      namespace util {
        class com.example.wemeet.util.ReturnVO {
            - code : Integer
            - message : String
            + ReturnVO()
            + equals()
            + getCode()
            + getMessage()
            + hashCode()
            + setCode()
            + setMessage()
            + toString()
            # canEqual()
        }
      }
    }
  }
  

  com.example.wemeet.util.MarkerInfo o-- com.example.wemeet.pojo.Bug : bug


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
